#!/usr/bin/env bash
set -euo pipefail

# Independently verify the solution with `lake comparator`, the comparator that ships in this
# project's Lean toolchain: it builds `Challenge` and `Solution` in a `bwrap` sandbox, exports
# them, checks that the two theorems of comparator.json have the same statements in both and use
# no axiom beyond the permitted ones, and replays the solution through Lean's kernel and the
# toolchain's bundled independent kernels (nanoda and con-ron).
#
# Trust required: the Lean toolchain, Mathlib, Challenge.lean (the statements), lakefile.toml
# and lake-manifest.json. The proof in MIPRE-formalization need not be trusted.
#
# Adapted from PalomarRegistry/PalomarTemplate (`scripts/verify-comparator.sh`, Apache-2.0), as
# MIPRE-formalization's `scripts/palomar/verify-comparator.sh`.
repository_root=$(cd "$(dirname "$0")" && pwd)
cd "$repository_root"

for required_command in bwrap lake lean python3; do
  if ! command -v "$required_command" >/dev/null 2>&1; then
    echo "error: $required_command is required to run lake comparator" >&2
    exit 1
  fi
done

toolchain=$(tr -d '[:space:]' < lean-toolchain)
prefix=$(lean --print-prefix)
for tool in lake leanexport leanchecker nanoda_bin con-ron; do
  if [ ! -x "$prefix/bin/$tool" ]; then
    echo "error: toolchain $toolchain does not bundle $tool" >&2
    echo "lake comparator and the bundled kernels need leanprover/lean4:v4.35.0-rc2 or later" >&2
    exit 1
  fi
done

# Register the toolchain's bundled independent kernels, as Palomar does, in a generated copy of
# comparator.json.
config=$(mktemp "${TMPDIR:-/tmp}/comparator.XXXXXX")
trap 'rm -f "$config"' EXIT
python3 - comparator.json "$config" "$prefix" <<'PY'
import json
import pathlib
import sys

source, destination, prefix = sys.argv[1:]
try:
    config = json.loads(pathlib.Path(source).read_text(encoding="utf-8"))
except (OSError, UnicodeError, json.JSONDecodeError) as error:
    print(f"error: cannot read valid Comparator config {source}: {error}", file=sys.stderr)
    raise SystemExit(1)
if not isinstance(config, dict):
    print(f"error: {source} must contain one JSON object", file=sys.stderr)
    raise SystemExit(1)
if "external_kernels" in config:
    print(f"error: {source}: external_kernels is generated by this script; remove it", file=sys.stderr)
    raise SystemExit(1)
config.pop("enable_nanoda", None)
config["external_kernels"] = {
    "nanoda": [f"{prefix}/bin/nanoda_bin"],
    "con-ron": [f"{prefix}/bin/con-ron"],
}
pathlib.Path(destination).write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
PY

# Mathlib's cache only: MIPRE-formalization itself is compiled from source, inside the
# sandbox, when the comparator builds `Solution`.
lake exe cache get
# The kernels recurse deeply on some of the library's terms.
ulimit -s unlimited 2>/dev/null || ulimit -s "$(ulimit -Hs)"
lake comparator --config "$config"
